name: ecommerce_app
description: "Charlotte Folk"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  flutter_native_splash: ^2.4.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_logo.png
  web: true
